### ISSUE TITLE
MapTypes.fs Interface Generator Bug

### ISSUE THREAD

**Issue by halfAbee** [dotnet-websharper/google.maps#1]
Hi,

I've been trying to use google maps' style types, and I believe you have an unwanted line in MapTypes.fs at line 26:

```
  24: let MapTypeStyler =
  25: Config "MapTypeStyler"
  26: |+> Static [Constructor T]
```

If you comment out line 26 and rebuild, clients can use the `MapTypeStyler` type, otherwise there is a compiler error because of the extra constructor definition.

Here is some code that currently fails to compile (fixed above):

```
    [<JavaScript>]
    module GoogleMaps =
        open WebSharper.JavaScript
        open WebSharper.Google.Maps

        let mts = new MapTypeStyler()
```

**Comment by Jand42** [comment]
Fixed in commit 27f077d8084222d895ed49f7a0fdcc2d4633bb9e
